# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.celsius_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.celsius_label.setGeometry(QtCore.QRect(170, 110, 91, 21))
        self.celsius_label.setObjectName("celsius_label")
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(340, 70, 91, 21))
        self.result_label.setObjectName("result_label")
        self.celsius_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.celsius_input.setGeometry(QtCore.QRect(210, 180, 113, 22))
        self.celsius_input.setObjectName("celsius_input")
        self.convert_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.convert_button.setGeometry(QtCore.QRect(220, 270, 75, 24))
        self.convert_button.setObjectName("convert_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.celsius_label.setText(_translate("MainWindow", "Hallo Label Yeah"))
        self.result_label.setText(_translate("MainWindow", "Hallo Label noo"))
        self.celsius_input.setText(_translate("MainWindow", "Pack rein das zeug"))
        self.convert_button.setText(_translate("MainWindow", "Push man"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
